// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CompoundOSTreasury$Type } from "./CompoundOSTreasury";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CompoundOSTreasury"]: CompoundOSTreasury$Type;
    ["contracts/CompoundOSTreasury.sol:CompoundOSTreasury"]: CompoundOSTreasury$Type;
  }

  interface ContractTypesMap {
    ["CompoundOSTreasury"]: GetContractReturnType<CompoundOSTreasury$Type["abi"]>;
    ["contracts/CompoundOSTreasury.sol:CompoundOSTreasury"]: GetContractReturnType<CompoundOSTreasury$Type["abi"]>;
  }
}
